# Generated by Django 4.2.13 on 2024-05-12 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('idPregunta', models.AutoField(primary_key=True, serialize=False)),
                ('nombrePregunta', models.TextField()),
                ('categoriaPregunta', models.CharField(max_length=200)),
                ('respuestaPregunta', models.TextField()),
            ],
            options={
                'db_table': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='Intentos',
            fields=[
                ('idIntento', models.AutoField(primary_key=True, serialize=False)),
                ('fechaIntento', models.DateField()),
                ('fkUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
