# Generated by Django 4.2.13 on 2024-05-12 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('descripcionCategoria', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Categorias',
            },
        ),
        migrations.RemoveField(
            model_name='preguntas',
            name='categoriaPregunta',
        ),
        migrations.AlterModelTable(
            name='intentos',
            table='Intentos',
        ),
        migrations.AddField(
            model_name='preguntas',
            name='fkCategorias',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.categorias'),
        ),
    ]
