# Generated by Django 4.2.13 on 2024-05-12 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_categorias_remove_preguntas_categoriapregunta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntas',
            name='respuestaPregunta',
        ),
        migrations.AddField(
            model_name='intentos',
            name='fkCategorias',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.categorias'),
        ),
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('idRespuestas', models.AutoField(primary_key=True, serialize=False)),
                ('nombreRespuestas', models.TextField()),
                ('fkPregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.preguntas')),
            ],
            options={
                'db_table': 'Respuestas',
            },
        ),
        migrations.CreateModel(
            name='RegistroRespuestaPreguntas',
            fields=[
                ('idRespuestaPreguntas', models.AutoField(primary_key=True, serialize=False)),
                ('fkPregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.preguntas')),
                ('fkRespuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.respuestas')),
                ('fkUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'RespuestasPreguntas',
            },
        ),
    ]
