# Generated by Django 4.2.13 on 2024-05-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_preguntas_respuestapregunta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntas',
            name='nivelPregunta',
            field=models.CharField(default='Baja', max_length=300),
        ),
        migrations.AddField(
            model_name='preguntas',
            name='nombreTema',
            field=models.CharField(default='Gratuito', max_length=300),
        ),
    ]
