# Generated by Django 4.2.13 on 2024-05-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_registrorespuestapreguntas_numerointento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temarios',
            fields=[
                ('idTemarios', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTemario', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Temarios',
            },
        ),
        migrations.RemoveField(
            model_name='preguntas',
            name='nombreTema',
        ),
    ]
