# Generated by Django 4.2.13 on 2024-05-13 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_temarios_remove_preguntas_nombretema'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntas',
            name='fkTemarios',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.temarios'),
        ),
    ]
