# Generated by Django 4.2.13 on 2024-05-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_respuestas_fkcategorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntas',
            name='justificacionPregunta',
            field=models.TextField(default=''),
        ),
    ]
