# Generated by Django 4.2.13 on 2024-05-25 21:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_preguntas_justificacionpregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrorespuestapreguntas',
            name='fechaContestacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
