# Generated by Django 4.2.13 on 2024-06-02 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_activesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForoUsuarios',
            fields=[
                ('idForo', models.AutoField(primary_key=True, serialize=False)),
                ('mensajeForo', models.TextField()),
                ('valorMensaje', models.SmallIntegerField()),
                ('fk_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
