# Generated by Django 4.2.13 on 2024-06-05 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_forousuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogTema',
            fields=[
                ('idBlog', models.AutoField(primary_key=True, serialize=False)),
                ('titleTopic', models.TextField()),
                ('fk_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blogTema',
            },
        ),
        migrations.CreateModel(
            name='blogComentario',
            fields=[
                ('idBlogComentario', models.AutoField(primary_key=True, serialize=False)),
                ('comentarioTitle', models.TextField()),
                ('fk_Topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.blogtema')),
                ('fk_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blogComentario',
            },
        ),
    ]
