# Generated by Django 4.2.13 on 2024-06-06 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_blogtema_blogcomentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaypalPago',
            fields=[
                ('idPayment', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField()),
                ('monto_pago', models.CharField(max_length=255)),
                ('status_pago', models.CharField(max_length=255)),
                ('folio_pago', models.CharField(max_length=255)),
                ('fk_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PaypalPago',
            },
        ),
    ]
