# Generated by Django 4.2.13 on 2024-06-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_paypalpago_tipo_membresia'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntas',
            name='respuesta_incorrecta_dos',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='preguntas',
            name='respuesta_incorrecta_tres',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='preguntas',
            name='respuesta_incorrecta_uno',
            field=models.TextField(default=''),
        ),
    ]
