# Generated by Django 4.2.13 on 2024-06-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_panelinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelinformation',
            name='texto_referencia',
            field=models.TextField(default=''),
        ),
    ]
