# Generated by Django 4.2.13 on 2024-06-12 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_panelinformation_tipoblog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntas',
            name='respuesta_incorrecta_dos',
        ),
        migrations.RemoveField(
            model_name='preguntas',
            name='respuesta_incorrecta_tres',
        ),
        migrations.RemoveField(
            model_name='preguntas',
            name='respuesta_incorrecta_uno',
        ),
    ]
