# Generated by Django 4.2.13 on 2024-06-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_preguntas_respuesta_incorrecta_dos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestas',
            name='statusRespuestas',
            field=models.TextField(default='Correcto'),
        ),
    ]
