# Generated by Django 4.2.13 on 2024-06-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_respuestas_statusrespuestas'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntas',
            name='tipoPregunta',
            field=models.TextField(default='Continua'),
        ),
    ]
