# Generated by Django 4.2.13 on 2024-06-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_preguntas_tipopregunta'),
    ]

    operations = [
        migrations.CreateModel(
            name='CantidadPagos',
            fields=[
                ('idCantidad', models.AutoField(primary_key=True, serialize=False)),
                ('cantidadPago', models.CharField(max_length=255)),
                ('tipoMembresia', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'CantidadPagos',
            },
        ),
    ]
