# Generated by Django 4.2.13 on 2024-06-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_cantidadpagos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantidadpagos',
            name='cantidadPago',
            field=models.FloatField(),
        ),
    ]
